version: '3'

services:
  users-db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: microverse
      POSTGRES_PASSWORD: microverse
    volumes:
      - users-db-data:/var/lib/users-db

  users-api:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment:
      DATABASE_HOST: users-db
      DATABASE_USERNAME: microverse
      DATABASE_PASSWORD: microverse
      USERS_API_KEY: ${USERS_API_KEY}
    volumes:
      - .:/users-api
    ports:
      - "3001:3001"
    depends_on:
      - users-db
    tty: true
    stdin_open: true

volumes:
  users-db-data:
    driver: local
